[[main]]
    title = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[main]]
    title = "Downloads"
    weight = 2
    identifier = "downloads"
    url = "/downloads/"

[[main]]
    title = "Documentation"
    weight = 3
    identifier = "docs"
    url = "/documentation/"

[[main]]
    title = "Blog"
    weight = 4
    identifier = "blog"
    url = "/blog/"

[[main]]
    title = "Contribute"
    weight = 5
    identifier = "contribute"
    url = "/contribute/"

[[main]]
    title = "About"
    weight = 6
    identifier = "about"
    url = "/about/"

[[footer]]
    title = "Contact"
    weight = 1
    identifier = "contact"
    url = "/contact/"

[[footer]]
    title = "Security"
    weight = 2
    identifier = "security"
    url = "/security/"

[[footer]]
    title = "Privacy"
    weight = 3
    identifier = "privacy"
    url = "/privacy/"

[[footer]]
    title = "Sponsors"
    weight = 4
    identifier = "sponsors"
    url = "/sponsors/"

[[footer]]
    title = "Mumble on GitHub"
    weight = 5
    identifier = "githublink"
    url = "https://github.com/mumble-voip"

